# Generated by Django 4.2.1 on 2023-05-08 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre y Apellido:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('contacto_tipo', models.IntegerField(choices=[[0, 'Pedir informacion'], [1, 'Mandar una queja'], [3, 'Sugerir, recomendar']], verbose_name='Tipo de Contacto')),
                ('subscripcion', models.BooleanField(default=False, verbose_name='Recibir correos de productos e inforcacion')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envio')),
            ],
        ),
    ]
